name: Auto Pull Request and Merge
permissions:
  contents: write
  pull-requests: write
  actions: write
on:

  push:
    branches:
      - feature-new-color

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ github.ref_name }}
          title: "Automated PR: Update Colors"
          body: "This PR automatically updates colors in the style-media.css file."
          labels: "auto-pr"

      - name: Approve Pull Request
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Pull Request
        uses: pascalgn/automerge-action@v0.15.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pull-request: ${{ steps.create-pr.outputs.pull-request-number }}
          merge-method: squash
