name: Create and Merge Pull Request

permissions:
  contents: write
  pull-requests: write
  issues: write  # Required for approving PRs
  actions: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.create_pr.outputs.pull-request-number }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Check if auto-pr-branch exists
        id: check_branch
        run: |
          if git ls-remote --heads origin auto-pr-branch | grep -q "auto-pr-branch"; then
            echo "Branch auto-pr-branch exists, checking out..."
            git checkout -t origin/auto-pr-branch
            git pull origin auto-pr-branch
          else
            echo "Branch auto-pr-branch does not exist, creating it..."
            git checkout -b auto-pr-branch
            git push origin auto-pr-branch
          fi

      - name: Ensure changes exist (Force Dummy Commit)
        run: |
          echo "Triggering PR - $(date)" >> .pr-trigger-file
          git add .pr-trigger-file
          git commit -m "Trigger PR - $(date)" || echo "No changes to commit"
          git push origin auto-pr-branch

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: auto-pr-branch
          title: "Auto PR: Sync main changes"
          body: "This PR is automatically created to update main via an intermediate branch."
          delete-branch: false
          draft: false

      - name: Debug PR Number
        run: 'echo "PR Number is: ${{ steps.create_pr.outputs.pull-request-number }}"'

  approve-pr:
    runs-on: ubuntu-latest
    needs: create-pull-request
    if: ${{ needs.create-pull-request.outputs.pr_number != '' && needs.create-pull-request.outputs.pr_number != null }}
    steps:
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1 
        with:
          github-token: ${{ secrets.APPROVER_DEMO }}
          number: ${{ needs.create-pull-request.outputs.pr_number }}

  merge-pr:
    runs-on: ubuntu-latest
    needs: approve-pr
    if: ${{ needs.create-pull-request.outputs.pr_number != '' && needs.create-pull-request.outputs.pr_number != null }}
    steps:
      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ needs.create-pull-request.outputs.pr_number }}
          method: squash
