name: Create and Merge Pull Request

permissions:
  contents: write
  pull-requests: write
  actions: write

on:
  push:
    branches:
      - main  # Trigger workflow when changes are pushed to main
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.create_pr.outputs.pull-request-number }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main  # Ensures we are on the main branch

      - name: Configure Git User  # ✅ Fix for "Please tell me who you are" error
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check if auto-pr-branch exists
        id: check_branch
        run: |
          if git ls-remote --heads origin auto-pr-branch | grep -q "auto-pr-branch"; then
            echo "Branch auto-pr-branch exists, checking out..."
            git checkout auto-pr-branch
            git pull origin auto-pr-branch
          else
            echo "Branch auto-pr-branch does not exist, creating it..."
            git checkout -b auto-pr-branch
            git push origin auto-pr-branch
          fi

      - name: Ensure auto-pr-branch is up-to-date
        run: |
          git checkout auto-pr-branch
          git pull origin main
          git push origin auto-pr-branch

      - name: Make a small change to force PR creation
        run: |
          echo "Trigger PR $(date)" > dummy.txt
          git add dummy.txt
          git commit -m "Trigger PR creation workflow"
          git push origin auto-pr-branch

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: auto-pr-branch
          title: "Auto PR: Sync main changes"
          body: "This PR is automatically created to update main via an intermediate branch."
          delete-branch: false  # Keep PR open until merged
          draft: false  # Ensure PR is ready for review

      - name: Debug PR Number
        run: echo "PR Number is ${{ steps.create_pr.outputs.pull-request-number }}"

  approve-pr:
    runs-on: ubuntu-latest
    needs: create-pull-request
    if: needs.create-pull-request.outputs.pr_number != ''
    steps:
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.APPROVER_DEMO }}
          number: ${{ needs.create-pull-request.outputs.pr_number }}

  merge-pr:
    runs-on: ubuntu-latest
    needs: approve-pr
    if: needs.create-pull-request.outputs.pr_number != ''
    steps:
      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ needs.create-pull-request.outputs.pr_number }}
          method: squash
