name: Create and Merge Pull Request

permissions:
  contents: write
  pull-requests: write
  actions: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.create_pr.outputs.pull-request-number }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0  # Ensures complete branch history

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Check if auto-pr-branch exists
        id: check_branch
        run: |
          if git ls-remote --heads origin auto-pr-branch | grep -q "auto-pr-branch"; then
            echo "Branch auto-pr-branch exists, checking out..."
            git checkout -t origin/auto-pr-branch
            git pull origin auto-pr-branch
          else
            echo "Branch auto-pr-branch does not exist, creating it..."
            git checkout -b auto-pr-branch
            git push origin auto-pr-branch
          fi

      - name: Ensure changes exist (Dummy Commit if needed)
        run: |
          if git diff --quiet origin/main..auto-pr-branch; then
            echo "No changes detected, making a dummy commit."
            echo "Triggering PR - $(date)" >> .pr-trigger-file
            git add .pr-trigger-file
            git commit -m "Trigger PR - $(date)"
            git push origin auto-pr-branch
          else
            echo "Changes detected, proceeding with PR creation."
          fi

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.APPROVER_DEMO }}
          base: main
          branch: auto-pr-branch
          title: "Auto PR: Sync main changes"
          body: "This PR is automatically created to update main via an intermediate branch."
          delete-branch: false
          draft: false
          assignees: SamirMohamed24
          reviewers: SamirMohamed24
          commit-message: "[create-pull-request] automated change"

  approve-pr:
    runs-on: ubuntu-latest
    needs: create-pull-request
    if: needs.create-pull-request.outputs.pr_number != ''
    steps:
      - name: Wait for PR creation
        run: sleep 10  # Small delay to ensure PR is fully processed

      - name: Approve Pull Request
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.APPROVER_DEMO }}

  merge-pr:
    runs-on: ubuntu-latest
    needs: approve-pr
    if: needs.create-pull-request.outputs.pr_number != ''
    steps:
      - name: Wait before merging
        run: sleep 10  # Small delay before merging

      - name: Merge Pull Request
        uses: pascalgn/automerge-action@v0.15.6
        with:
          github-token: ${{ secrets.APPROVER_DEMO }}
          pull-request: ${{ needs.create-pull-request.outputs.pr_number }}
          merge-method: squash
          delete-branch: true  # Deletes the auto-pr-branch after merging
