name: Auto Merge Bot PR (With PAT for Branch Protection Override)

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Auto Merge PR using PAT
        if: github.event.pull_request.user.login == 'github-actions[bot]'
        env:
          GH_TOKEN: ${{ secrets.APPROVER_DEMO }}
        run: |
          # Authenticate using the PAT from the APPROVER_DEMO secret
          echo "$GH_TOKEN" | gh auth login --with-token
          
          # Attempt to merge the PR automatically
          gh pr merge ${{ github.event.pull_request.number }} --merge --repo ${{ github.repository }}
