name: Create and Merge Pull Request

permissions:
  contents: write
  pull-requests: write
  issues: write  # Required for approving PRs
  actions: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.create_pr.outputs.pull-request-number }}  # Use direct step reference
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Check if auto-pr-branch exists
        id: check_branch
        run: |
          if git ls-remote --heads origin auto-pr-branch | grep -q "auto-pr-branch"; then
            echo "Branch auto-pr-branch exists, checking out..."
            git checkout -t origin/auto-pr-branch
            git pull origin auto-pr-branch
          else
            echo "Branch auto-pr-branch does not exist, creating it..."
            git checkout -b auto-pr-branch
            git push origin auto-pr-branch
          fi

      - name: Ensure changes exist (Dummy Commit if needed)
        run: |
          if git diff --quiet origin/main..auto-pr-branch; then
            echo "No changes detected, making a dummy commit."
            echo "Triggering PR - $(date)" >> .pr-trigger-file
            git add .pr-trigger-file
            git commit -m "Trigger PR - $(date)"
            git push origin auto-pr-branch
          else
            echo "Changes detected, proceeding with PR creation."
          fi

      - name: Create Pull Request
        id: create_pr  # Step ID must match reference
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Change back to GITHUB_TOKEN if needed
          base: main
          branch: auto-pr-branch
          title: "Auto PR: Sync main changes"
          body: "This PR is automatically created to update main via an intermediate branch."
          delete-branch: true  # Ensure PR branch is deleted after merge
          draft: false

      - name: Debug PR Number
        run: 'echo "PR Number: ${{ steps.create_pr.outputs.pull-request-number }}"'  # Direct step reference

  approve-pr:
    runs-on: ubuntu-latest
    needs: create-pull-request
    steps:
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.APPROVER_DEMO }}
          number: ${{ needs.create-pull-request.outputs.pr_number }}  # Ensure correct reference

  merge-pr:
    runs-on: ubuntu-latest
    needs: approve-pr
    steps:
      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ needs.create-pull-request.outputs.pr_number }}  # Ensure correct reference
          method: squash
