name: Auto Create, Approve & Merge PR

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pr:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make Changes
        run: |
          echo "Automated change at $(date)" >> auto-change.txt
          git add auto-change.txt

      - name: Check for Changes
        id: check
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "::set-output name=has_changes::true"
          else
            echo "::set-output name=has_changes::false"
          fi

      - name: Create Branch, Commit and Push Changes
        if: steps.check.outputs.has_changes == 'true'
        run: |
          # Create a new branch based on the current commit
          BRANCH_NAME="auto-pr-$(date +%s)"
          git checkout -b "$BRANCH_NAME"
          # Configure git user details
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          # Commit changes if there are any changes
          git commit -m "Updated mkdocs files [Automated Run]" || echo "No changes to commit"
          # Pull latest changes from main with rebase to avoid conflicts
          git pull --rebase origin main
          # Push the new branch to origin with upstream tracking set
          git push --set-upstream origin "$BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create Pull Request
        if: steps.check.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ env.BRANCH_NAME }}
          title: "Automated PR: Sync main changes"
          body: "This PR is automatically created by GitHub Actions."

  auto_approve_and_merge:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Auto-Approve PR
        # This step runs only if the PR title indicates an automated PR.
        if: contains(github.event.pull_request.title, 'Automated PR:')
        env:
          GH_TOKEN: ${{ secrets.APPROVER_DEMO }}
        run: |
          echo "$GH_TOKEN" | gh auth login --with-token
          gh pr review ${{ github.event.pull_request.number }} --approve --repo ${{ github.repository }}

      - name: Auto-Merge PR
        if: contains(github.event.pull_request.title, 'Automated PR:')
        env:
          GH_TOKEN: ${{ secrets.APPROVER_DEMO }}
        run: |
          echo "$GH_TOKEN" | gh auth login --with-token
          gh pr merge ${{ github.event.pull_request.number }} --merge --repo ${{ github.repository }}
