name: Auto Create, Approve & Merge PR

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pr:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make Changes
        run: |
          echo "Automated change at $(date)" >> auto-change.txt
          git add auto-change.txt

      - name: Check for Changes
        id: check
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "has_changes=true" >> $GITHUB_ENV
          else
            echo "has_changes=false" >> $GITHUB_ENV
          fi

      - name: Create Branch and Commit
        if: env.has_changes == 'true'
        run: |
          BRANCH_NAME="auto-pr-$(date +%s)"
          git checkout -b "$BRANCH_NAME"
          git commit -m "Automated commit: Update auto-change.txt" || echo "No changes to commit"
          git push origin "$BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create Pull Request
        if: env.has_changes == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ env.BRANCH_NAME }}
          title: "Automated PR: Sync main changes"
          body: "This PR is automatically created by GitHub Actions."

  auto_approve_and_merge:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Auto-Approve PR
        if: github.event.pull_request.user.login == 'github-actions[bot]'
        env:
          GH_TOKEN: ${{ secrets.APPROVER_DEMO }}
        run: |
          # Authenticate using the admin/owner PAT
          echo "$GH_TOKEN" | gh auth login --with-token
          # Approve the pull request
          gh pr review ${{ github.event.pull_request.number }} --approve --repo ${{ github.repository }}

      - name: Auto-Merge PR
        if: github.event.pull_request.user.login == 'github-actions[bot]'
        env:
          GH_TOKEN: ${{ secrets.APPROVER_DEMO }}
        run: |
          # Authenticate using the admin/owner PAT
          echo "$GH_TOKEN" | gh auth login --with-token
          # Merge the pull request
          gh pr merge ${{ github.event.pull_request.number }} --merge --repo ${{ github.repository }}
